### ISSUE TITLE
Q: Copy multiple files?

### ISSUE THREAD

**Issue by ClydeDz** [canastro/copy-action#2]
Hi Ricardo,
Could you please add an example of how one would copy multiple files using this action?
Cheers!

**Comment by plorencrstit** [comment]
```
- name: Copy icons
        uses: canastro/copy-file-action@master
        with:
          source: packages/website/icons/.
          target: packages/public/icons/
          flags: '-r'
```
